Add bash to Dockerfile, add additional service and logging
tunix/digitalocean-dyndns pull request #16
Opened 2020-12-13 22:10 UTC by otherguy

Supersedes https://github.com/tunix/digitalocean-dyndns/pull/15

2020-12-13 22:13 UTC, otherguy commented on dyndns.sh
> +        test -n "$ip" && break
Indent was incorrect

2020-12-14 10:00 UTC, tunix requested changes

2020-12-14 10:00 UTC, tunix commented on dyndns.sh
> +              echo "existing DNS record address ($record_data) did not need updating"
The indentation on this line should 4. Currently it's 2.

2020-12-14 10:01 UTC, merged

2020-12-14 10:15 UTC, otherguy commented
Awesome, thanks for merging! Works perfectly:

<img width="1248" alt="Screen Shot 2020-12-14 at 11 14 55" src="https://user-images.githubusercontent.com/6072721/102069150-a9d10480-3dfd-11eb-9d35-e96a5d3c0684.png">