Fix breakage when there are multiple DNS records for a single subdomain
tunix/digitalocean-dyndns pull request #22
Opened 2021-06-17 04:09 UTC by lawtancool

Previously, the script would fail to update the DNS for a subdomain if there were multiple existing records. With this PR, the script will check for duplicate records and automatically delete all but one of them.

2021-06-22 21:18 UTC, tunix requested changes
Can you please make this change optional and disabled by default? We can simply pass an environment variable and enable this feature.

2021-06-22 22:47 UTC, lawtancool commented
@tunix What should the default behavior be then? Should the script just throw an error and not update the record if there are duplicates?

2021-06-22 22:49 UTC, tunix commented
I think it should continue as is. Failing with a proper message can be an option as well. I think, we should not delete records by default.

2021-07-05 00:32 UTC, lawtancool commented
Hi @tunix! I've added a new environment variable `REMOVE_DUPLICATES` which is `"false"` by default, and I also added documentation to the README.

2021-07-08 22:11 UTC, tunix approved these changes

2021-07-08 22:11 UTC, merged